CREATE TABLE  IF NOT EXISTS comments (
    id SERIAL PRIMARY KEY,
    author INTEGER REFERENCES users(id) ON DELETE SET NULL,
    post INTEGER REFERENCES posts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    replying_to INTEGER REFERENCES comments(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);